apiVersion: v1
kind: Service
metadata:
  name: my-demo
  namespace: test
  labels:
    app.kubernetes.io/name: my-demo
  annotations:
    metallb.universe.tf/address-pool: my-ip-pool
spec:
  selector:
    app.kubernetes.io/name: my-demo
  type: ClusterIP
  ports:
    - port: 6500
      name: http-6500
      targetPort: 6500
      protocol: TCP
